proxy-groups:
  # 手动选择（机场多节点 / 自建1-2个都能用）
  - name: 手动选择
    type: select
    proxies: []

  # 自动选择（测速）
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies: []

  # GitHub
  - name: GitHub
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # chatgpt
  - name: chatgpt
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # AI服务
  - name: AI服务
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # YouTube
  - name: YouTube
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # Netflix
  - name: Netflix
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # 国外媒体
  - name: 国外媒体
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # 微软服务
  - name: 微软服务
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # 谷歌服务
  - name: 谷歌服务
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # 苹果服务
  - name: 苹果服务
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # 游戏平台
  - name: 游戏平台
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # STEAM
  - name: STEAM
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连

  # 全球直连
  - name: 全球直连
    type: select
    proxies:
      - DIRECT

  # 漏网之鱼
  - name: 漏网之鱼
    type: select
    proxies:
      - 自动选择
      - 手动选择
      - 全球直连
